### ISSUE TITLE
Maybe an implementation with VideoView?

### ISSUE THREAD

**Issue by mauriciogior** [ButterflyTV/LibRtmp-Client-for-Android#1]
Hello, do you have an open source implementation of a `VideoView` widget that uses your `RtmpClient`?

Thanks

**Comment by mekya** [comment]
Hi Mauricio,

There is a kind of video view widget, it is called exoplayer.
http://developer.android.com/guide/topics/media/exoplayer.html

The exoplayer we have forked uses RtmpClient to play files.
https://github.com/ButterflyTV/ExoPlayer-with-RTMP-and-FLV-seek

This fork supports armeabi -v7a architecture for rtmpclient. If you plan to
use this player, we can update this player to support all architectures.

Bests,
A. Oguz

**Comment by mauriciogior** [comment]
@mekya Thank you!
Do you have instructions on how to compile for other architectures?

**Comment by mekya** [comment]
You're welcome ;)

If you build the library with the latest version of master branch, it will
support for all architectures(x86, arm64, armv7, mips. etc.)



On Fri, Feb 19, 2016 at 3:21 PM, Maurício Giordano <notifications@github.com

**Comment by mekya** [comment]
Closing this issue.
