### ISSUE TITLE
Publish stream

### ISSUE THREAD

**Issue by iSinch** [ButterflyTV/LibRtmp-Client-for-Android#12]
Hello. i am trying publishing my video from camera, but I don't know how to use you're method `writeVideo`  . I should get byte array from camera ?

```
  rtmpMuxer.open("rtmp://mysite.com/streamName");
  rtmpMuxer.writeVideo(byte[] data, int offset, int length, int timestamp);
```

**Comment by zackexplosion** [comment]
May I see how you resolve this? I have same issue too. what is the length param?
