### ISSUE TITLE
Library update

### ISSUE THREAD

**Issue by iSinch** [ButterflyTV/LibRtmp-Client-for-Android#13]
Hello :)
I see that you have an update in your project and edit some methods
Can you update gradle dependencies  and readme in GitHub?

**Comment by mekya** [comment]
:) Thank you. 

Updated. 

Ok?

**Comment by iSinch** [comment]
@mekya  thanks' u :)
Could you tell me,please, how can I decode to h264 frames from camera ?

**Comment by mekya** [comment]
Decoding h264 frames is actually a different job.  What do you want to do by decoding frames?

You may want to look at some projects about that. 
https://github.com/artclarke/humble-video
https://ffmpeg.org/

**Comment by iSinch** [comment]
> What do you want to do by decoding frames?

It's for `write` in your library.

 

> Write h264 nal units with this function

**Comment by iSinch** [comment]
Ops, my mistake: I mean how to ENCODE frames from camera to h264*

**Comment by mekya** [comment]
Hi @iSinch ,

I recommend you to use Android Media Codec 
https://developer.android.com/reference/android/media/MediaCodec.html

Probably you may want to look at a sample code. Here is the grafika
https://github.com/google/grafika

Nevertheless, it seems a little complex at first glance. 

Sorry for late reply.

**Comment by justinshaohi** [comment]
Hello @mekya 
is it only support publish h264 ?

**Comment by mekya** [comment]
Yeah unfourtunately muxer supports only H264. Sorry for that :(

**Comment by justinshaohi** [comment]
hi @mekya 
i want to publish，i call native methon open(rtmpurl,width,height) firstly, it return -3。
that why？
sorry for my poor c++ :(

**Comment by mekya** [comment]
Hmm -3 means there is a problem in connecting to server
https://github.com/ButterflyTV/LibRtmp-Client-for-Android/blob/28d531cd6999960dcb9156d2ff2ff9e433c9c55c/rtmp-client/src/main/jni/flvmuxer/xiecc_rtmp.c#L167

Please make sure your server is configured correctly and accepts your connection.

**Comment by iSinch** [comment]
@mekya 
Hey )
I have a suggestion - MayBe you modify return new value ? for example, when server respone code 403 ?

**Comment by mekya** [comment]
Yeah @iSinch you're right. Do you ever think modifying this code and making a pull request?

**Comment by iSinch** [comment]
@mekya I will make it soon

**Comment by mekya** [comment]
Hey @iSinch,
Closing this issue. You can make pull request whenever you are ready.

Cheers
m.
