### ISSUE TITLE
Is there any sample to test rtmp muxer to write video and audio

### ISSUE THREAD

**Issue by bingdow** [ButterflyTV/LibRtmp-Client-for-Android#14]
I've found these methods in muxer class.
Is there any doc or developer guide can help me test publish data to rtmp server?

**Comment by mekya** [comment]
Hi @bingdow 
The only document is [ReadMe page](https://github.com/ButterflyTV/LibRtmp-Client-for-Android). 

What exactly do you want to learn? I can write it here and added to ReadMe page later.

**Comment by davidarchi** [comment]
Can you give a sample to publish video and audio to rtmp server?
