### ISSUE TITLE
READ_PHONE_STATE permission

### ISSUE THREAD

**Issue by calber** [ButterflyTV/LibRtmp-Client-for-Android#15]
as there is no minSdkSupport defined, 1 is assumed. this cause any project including this library to request Permission READ_PHONE_STATE. Which is bad if app is not actually making Phone calls!

**Comment by mekya** [comment]
It seems really weird. We have compiled the source code for sdkVersion 16. 

There are some compatibility issues in ndk if library run in a device whose version below the compiled versions.  

Then I am going to make minSdkVersion to 16. Is it ok for you? 

Sorry for late reply. 

Bests,
A. Oguz

**Comment by calber** [comment]
for me yes

**Comment by mekya** [comment]
minSdkVersion is set to 16 and a new version is on the repo with version 0.2.6.1

**Comment by calber** [comment]
sorry, needs sdk 23 #9

**Comment by mekya** [comment]
As with the discussion on #9 , setting compileSdk 23 causes some troubles.

Closing this issue, we can continue discussing this issue. Please feel free to comment.
