### ISSUE TITLE
Does not sure about rmtpMuxer.writeVideo()

### ISSUE THREAD

**Issue by insthync** [ButterflyTV/LibRtmp-Client-for-Android#23]
Hi, I've try to create screen cast application, I've use **MediaCodec** with mime type = "video/avc" to receive buffer from **VirtualDisplay** but I does not sure that when I call I've did it wrong or not

            // Receive buffer from MediaCodec object
            ByteBuffer encodedData = mEncoder.getOutputBuffer(index);
            encodedData.position(mBufferInfo.offset);
            encodedData.limit(mBufferInfo.offset + mBufferInfo.size);
            
            // Set byte[] which will be sent to RMTP server
            byte[] bytes = new byte[encodedData.remaining()];
            encodedData.get(bytes);

            int rtmpConnectionState = mRTMPMuxer != null ? mRTMPMuxer.isConnected() : 0;
            if (rtmpConnectionState != 0) {
                int writeResult = mRTMPMuxer.writeVideo(bytes, 0, bytes.length, (int)System.currentTimeMillis());
            }

When I sent data to server I got **writeResult** = -1 then RMTP connection is disconnect.
You can see my project here: https://github.com/insthync/AndroidSimpleScreenRTMP

**Comment by insthync** [comment]
It going to disconnect after I does moveTaskToBack(true); in the activity. Now it's not always disconnect but still can not see the video via VLC

**Comment by insthync** [comment]
I have sent video data to server before send frame data video. recording video to server is fine but can not watching video live.

**Comment by 1612052** [comment]
did you find out the solution?
