### ISSUE TITLE
RTMP url not working

### ISSUE THREAD

**Issue by JulianZhao** [ButterflyTV/LibRtmp-Client-for-Android#3]
Hi, thank for your work. I want to use this:
[https://github.com/ButterflyTV/ExoPlayer-with-RTMP-and-FLV-seek](https://github.com/ButterflyTV/ExoPlayer-with-RTMP-and-FLV-seek)

I tried to play this url rtmp://ossrs.net:1935/live/livestream, but it's not working. I can play this url using other players, and I don't know why, so I make this issue.

Thanks.

**Comment by mekya** [comment]
Hi Julian,

Yeah it plays in other players. I am gonna check why it does not play on
this player when i have some time.

Bests,
A. Oguz

**Comment by JulianZhao** [comment]
@mekya Thank you. Hope that you have some time soon. I am not familiar with low-level development with ffmpeg and rtmp, I'm afraid that I can't solve this problem myself.   
I test several urls, It seems that exoplayer can't play stream without audio. 
I use nginx-rtmp, transport IPCamera's RTSP into RTMP and HLS (H264 with no audio),  exoplayer can't play my RTMP and HLS.

**Comment by mekya** [comment]
Good news. It can play right now ;)

Your stream is the last stream on the list. Check it out. 
https://github.com/ButterflyTV/ExoPlayer-with-RTMP-and-FLV-seek

Problem is not about RtmpClient. It is about Metadata Parser. Here is the last commit.
https://github.com/ButterflyTV/ExoPlayer-with-RTMP-and-FLV-seek/commit/ff58cdf11897619734dd429c9ab6188abd933e10

**Comment by JulianZhao** [comment]
@mekya Thank you so much! I tried and it's working now.

However, unfortunately, I meet some "bad stream" again. As I said at last post, I use [nginx-rtmp](https://github.com/arut/nginx-rtmp-module) to transport IPCamera's RTSP into RTMP and HLS, all of them can't be played with exoplayer.  The stream was encoded with H264 without audio:

```
Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720, 24.92 tbr, 90k tbn, 180k tbc
Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp
```
Is it about Metadata Parser too?
For some reason, I send my test urls to you by email, may be you can check them when you have some time. Thanks again.

**Comment by mekya** [comment]
ok never mind.

As you said, this is another issue. Let's continue via email.
