### ISSUE TITLE
have you tested the RtmpMuxer publish api? 

### ISSUE THREAD

**Issue by notedit** [ButterflyTV/LibRtmp-Client-for-Android#4]
i use  RtmpMuxer in my project,  but i play  is black.

**Comment by notedit** [comment]
the audio is ok

**Comment by notedit** [comment]
Stream #0:0: Video: h264, none, 1k tbr, 1k tbn, 2k tbc

**Comment by notedit** [comment]
it is my fault, i do not send the pps

**Comment by mekya** [comment]
I hope everything is ok on your side right now. 

Good luck
